version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-spam-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATASET_FILE=data/spam_dataset.csv
      - COMMAND_PREFIX=!
      - FLAG_COMMAND=!flag
      - CONFIG_PATH=data/server_config.json
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 